version: "3.9"
services:
  backend:
    build: .
    ports:
      - 8080:8080

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spotdiff_staging
      POSTGRES_USER: spotdiff

    volumes:
      - ./data/db:/var/lib/postgresql/data

    ports:
      - 5432:5432
